// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUM_NAGOX_ENUM_H_
#define FLATBUFFERS_GENERATED_ENUM_NAGOX_ENUM_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 24,
             "Non-compatible flatbuffers version included");

namespace Nagox {
namespace Enum {

enum LOGIN_RESULT : uint8_t {
  LOGIN_RESULT_FAIL = 0,
  LOGIN_RESULT_SUCCESS = 1,
  LOGIN_RESULT_DUPLICATE = 2,
  LOGIN_RESULT_NONE = 3,
  LOGIN_RESULT_MIN = LOGIN_RESULT_FAIL,
  LOGIN_RESULT_MAX = LOGIN_RESULT_NONE
};

inline const LOGIN_RESULT (&EnumValuesLOGIN_RESULT())[4] {
  static const LOGIN_RESULT values[] = {
    LOGIN_RESULT_FAIL,
    LOGIN_RESULT_SUCCESS,
    LOGIN_RESULT_DUPLICATE,
    LOGIN_RESULT_NONE
  };
  return values;
}

inline const char * const *EnumNamesLOGIN_RESULT() {
  static const char * const names[5] = {
    "FAIL",
    "SUCCESS",
    "DUPLICATE",
    "NONE",
    nullptr
  };
  return names;
}

inline const char *EnumNameLOGIN_RESULT(LOGIN_RESULT e) {
  if (::flatbuffers::IsOutRange(e, LOGIN_RESULT_FAIL, LOGIN_RESULT_NONE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLOGIN_RESULT()[index];
}

enum GROUP_TYPE : uint8_t {
  GROUP_TYPE_PLAYER = 0,
  GROUP_TYPE_MONSTER = 1,
  GROUP_TYPE_NPC = 2,
  GROUP_TYPE_DROP_ITEM = 3,
  GROUP_TYPE_HARVEST = 4,
  GROUP_TYPE_MIN = GROUP_TYPE_PLAYER,
  GROUP_TYPE_MAX = GROUP_TYPE_HARVEST
};

inline const GROUP_TYPE (&EnumValuesGROUP_TYPE())[5] {
  static const GROUP_TYPE values[] = {
    GROUP_TYPE_PLAYER,
    GROUP_TYPE_MONSTER,
    GROUP_TYPE_NPC,
    GROUP_TYPE_DROP_ITEM,
    GROUP_TYPE_HARVEST
  };
  return values;
}

inline const char * const *EnumNamesGROUP_TYPE() {
  static const char * const names[6] = {
    "PLAYER",
    "MONSTER",
    "NPC",
    "DROP_ITEM",
    "HARVEST",
    nullptr
  };
  return names;
}

inline const char *EnumNameGROUP_TYPE(GROUP_TYPE e) {
  if (::flatbuffers::IsOutRange(e, GROUP_TYPE_PLAYER, GROUP_TYPE_HARVEST)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGROUP_TYPE()[index];
}

enum PLAYER_TYPE : uint8_t {
  PLAYER_TYPE_WARRIOR = 0,
  PLAYER_TYPE_PRIEST = 1,
  PLAYER_TYPE_ARCHER = 2,
  PLAYER_TYPE_MIN = PLAYER_TYPE_WARRIOR,
  PLAYER_TYPE_MAX = PLAYER_TYPE_ARCHER
};

inline const PLAYER_TYPE (&EnumValuesPLAYER_TYPE())[3] {
  static const PLAYER_TYPE values[] = {
    PLAYER_TYPE_WARRIOR,
    PLAYER_TYPE_PRIEST,
    PLAYER_TYPE_ARCHER
  };
  return values;
}

inline const char * const *EnumNamesPLAYER_TYPE() {
  static const char * const names[4] = {
    "WARRIOR",
    "PRIEST",
    "ARCHER",
    nullptr
  };
  return names;
}

inline const char *EnumNamePLAYER_TYPE(PLAYER_TYPE e) {
  if (::flatbuffers::IsOutRange(e, PLAYER_TYPE_WARRIOR, PLAYER_TYPE_ARCHER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPLAYER_TYPE()[index];
}

enum NPC_TYPE : uint8_t {
  NPC_TYPE_CHIEF = 0,
  NPC_TYPE_CATAPULT = 1,
  NPC_TYPE_MIN = NPC_TYPE_CHIEF,
  NPC_TYPE_MAX = NPC_TYPE_CATAPULT
};

inline const NPC_TYPE (&EnumValuesNPC_TYPE())[2] {
  static const NPC_TYPE values[] = {
    NPC_TYPE_CHIEF,
    NPC_TYPE_CATAPULT
  };
  return values;
}

inline const char * const *EnumNamesNPC_TYPE() {
  static const char * const names[3] = {
    "CHIEF",
    "CATAPULT",
    nullptr
  };
  return names;
}

inline const char *EnumNameNPC_TYPE(NPC_TYPE e) {
  if (::flatbuffers::IsOutRange(e, NPC_TYPE_CHIEF, NPC_TYPE_CATAPULT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNPC_TYPE()[index];
}

enum MONSTER_TYPE : uint8_t {
  MONSTER_TYPE_FOX = 0,
  MONSTER_TYPE_SHEEP = 1,
  MONSTER_TYPE_BEAR = 2,
  MONSTER_TYPE_GOBLIN = 3,
  MONSTER_TYPE_BOSS = 4,
  MONSTER_TYPE_MIN = MONSTER_TYPE_FOX,
  MONSTER_TYPE_MAX = MONSTER_TYPE_BOSS
};

inline const MONSTER_TYPE (&EnumValuesMONSTER_TYPE())[5] {
  static const MONSTER_TYPE values[] = {
    MONSTER_TYPE_FOX,
    MONSTER_TYPE_SHEEP,
    MONSTER_TYPE_BEAR,
    MONSTER_TYPE_GOBLIN,
    MONSTER_TYPE_BOSS
  };
  return values;
}

inline const char * const *EnumNamesMONSTER_TYPE() {
  static const char * const names[6] = {
    "FOX",
    "SHEEP",
    "BEAR",
    "GOBLIN",
    "BOSS",
    nullptr
  };
  return names;
}

inline const char *EnumNameMONSTER_TYPE(MONSTER_TYPE e) {
  if (::flatbuffers::IsOutRange(e, MONSTER_TYPE_FOX, MONSTER_TYPE_BOSS)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMONSTER_TYPE()[index];
}

enum SKILL_TYPE : uint8_t {
  SKILL_TYPE_DEFAULT = 0,
  SKILL_TYPE_SKILL_1 = 1,
  SKILL_TYPE_MIN = SKILL_TYPE_DEFAULT,
  SKILL_TYPE_MAX = SKILL_TYPE_SKILL_1
};

inline const SKILL_TYPE (&EnumValuesSKILL_TYPE())[2] {
  static const SKILL_TYPE values[] = {
    SKILL_TYPE_DEFAULT,
    SKILL_TYPE_SKILL_1
  };
  return values;
}

inline const char * const *EnumNamesSKILL_TYPE() {
  static const char * const names[3] = {
    "DEFAULT",
    "SKILL_1",
    nullptr
  };
  return names;
}

inline const char *EnumNameSKILL_TYPE(SKILL_TYPE e) {
  if (::flatbuffers::IsOutRange(e, SKILL_TYPE_DEFAULT, SKILL_TYPE_SKILL_1)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSKILL_TYPE()[index];
}

enum EQUIPMENT_TYPE : uint8_t {
  EQUIPMENT_TYPE_WEAPON = 0,
  EQUIPMENT_TYPE_ARMOR = 1,
  EQUIPMENT_TYPE_MIN = EQUIPMENT_TYPE_WEAPON,
  EQUIPMENT_TYPE_MAX = EQUIPMENT_TYPE_ARMOR
};

inline const EQUIPMENT_TYPE (&EnumValuesEQUIPMENT_TYPE())[2] {
  static const EQUIPMENT_TYPE values[] = {
    EQUIPMENT_TYPE_WEAPON,
    EQUIPMENT_TYPE_ARMOR
  };
  return values;
}

inline const char * const *EnumNamesEQUIPMENT_TYPE() {
  static const char * const names[3] = {
    "WEAPON",
    "ARMOR",
    nullptr
  };
  return names;
}

inline const char *EnumNameEQUIPMENT_TYPE(EQUIPMENT_TYPE e) {
  if (::flatbuffers::IsOutRange(e, EQUIPMENT_TYPE_WEAPON, EQUIPMENT_TYPE_ARMOR)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEQUIPMENT_TYPE()[index];
}

enum NON_TARGET_TYPE : uint8_t {
  NON_TARGET_TYPE_PRIEST_PROJ = 0,
  NON_TARGET_TYPE_GOBLIN_PROJ = 1,
  NON_TARGET_TYPE_BOSS_PROJ_1 = 2,
  NON_TARGET_TYPE_BOSS_PROJ_2 = 3,
  NON_TARGET_TYPE_MIN = NON_TARGET_TYPE_PRIEST_PROJ,
  NON_TARGET_TYPE_MAX = NON_TARGET_TYPE_BOSS_PROJ_2
};

inline const NON_TARGET_TYPE (&EnumValuesNON_TARGET_TYPE())[4] {
  static const NON_TARGET_TYPE values[] = {
    NON_TARGET_TYPE_PRIEST_PROJ,
    NON_TARGET_TYPE_GOBLIN_PROJ,
    NON_TARGET_TYPE_BOSS_PROJ_1,
    NON_TARGET_TYPE_BOSS_PROJ_2
  };
  return values;
}

inline const char * const *EnumNamesNON_TARGET_TYPE() {
  static const char * const names[5] = {
    "PRIEST_PROJ",
    "GOBLIN_PROJ",
    "BOSS_PROJ_1",
    "BOSS_PROJ_2",
    nullptr
  };
  return names;
}

inline const char *EnumNameNON_TARGET_TYPE(NON_TARGET_TYPE e) {
  if (::flatbuffers::IsOutRange(e, NON_TARGET_TYPE_PRIEST_PROJ, NON_TARGET_TYPE_BOSS_PROJ_2)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNON_TARGET_TYPE()[index];
}

enum BOSS_FLY_TYPE : uint8_t {
  BOSS_FLY_TYPE_BOSS_FLY_TYPE_1 = 0,
  BOSS_FLY_TYPE_BOSS_FLY_TYPE_2 = 1,
  BOSS_FLY_TYPE_MIN = BOSS_FLY_TYPE_BOSS_FLY_TYPE_1,
  BOSS_FLY_TYPE_MAX = BOSS_FLY_TYPE_BOSS_FLY_TYPE_2
};

inline const BOSS_FLY_TYPE (&EnumValuesBOSS_FLY_TYPE())[2] {
  static const BOSS_FLY_TYPE values[] = {
    BOSS_FLY_TYPE_BOSS_FLY_TYPE_1,
    BOSS_FLY_TYPE_BOSS_FLY_TYPE_2
  };
  return values;
}

inline const char * const *EnumNamesBOSS_FLY_TYPE() {
  static const char * const names[3] = {
    "BOSS_FLY_TYPE_1",
    "BOSS_FLY_TYPE_2",
    nullptr
  };
  return names;
}

inline const char *EnumNameBOSS_FLY_TYPE(BOSS_FLY_TYPE e) {
  if (::flatbuffers::IsOutRange(e, BOSS_FLY_TYPE_BOSS_FLY_TYPE_1, BOSS_FLY_TYPE_BOSS_FLY_TYPE_2)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBOSS_FLY_TYPE()[index];
}

enum BOSS_MOVE_TYPE : uint8_t {
  BOSS_MOVE_TYPE_BOSS_MOVE_TYPE_1 = 0,
  BOSS_MOVE_TYPE_BOSS_MOVE_TYPE_2 = 1,
  BOSS_MOVE_TYPE_MIN = BOSS_MOVE_TYPE_BOSS_MOVE_TYPE_1,
  BOSS_MOVE_TYPE_MAX = BOSS_MOVE_TYPE_BOSS_MOVE_TYPE_2
};

inline const BOSS_MOVE_TYPE (&EnumValuesBOSS_MOVE_TYPE())[2] {
  static const BOSS_MOVE_TYPE values[] = {
    BOSS_MOVE_TYPE_BOSS_MOVE_TYPE_1,
    BOSS_MOVE_TYPE_BOSS_MOVE_TYPE_2
  };
  return values;
}

inline const char * const *EnumNamesBOSS_MOVE_TYPE() {
  static const char * const names[3] = {
    "BOSS_MOVE_TYPE_1",
    "BOSS_MOVE_TYPE_2",
    nullptr
  };
  return names;
}

inline const char *EnumNameBOSS_MOVE_TYPE(BOSS_MOVE_TYPE e) {
  if (::flatbuffers::IsOutRange(e, BOSS_MOVE_TYPE_BOSS_MOVE_TYPE_1, BOSS_MOVE_TYPE_BOSS_MOVE_TYPE_2)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBOSS_MOVE_TYPE()[index];
}

}  // namespace Enum
}  // namespace Nagox

#endif  // FLATBUFFERS_GENERATED_ENUM_NAGOX_ENUM_H_
