namespace Nagox.Enum;

enum LOGIN_RESULT: ubyte
{
    FAIL = 0,
    SUCCESS = 1,
    DUPLICATE = 2,
    NONE = 3
}

enum GROUP_TYPE: ubyte
{
    PLAYER = 0,
    MONSTER = 1,
    NPC = 2,
    DROP_ITEM = 3,

    HARVEST = 4
}

enum PLAYER_TYPE : ubyte
{
    WARRIOR = 0,
    PRIEST = 1,
    ARCHER = 2
}

enum NPC_TYPE : ubyte
{
   CHIEF = 0,
   CATAPULT = 1
}

enum MONSTER_TYPE : ubyte
{   FOX = 0,
    SHEEP = 1,
    BEAR = 2,
    GOBLIN = 3,
    BOSS = 4
}

enum SKILL_TYPE : ubyte
{
    DEFAULT = 0,
    SKILL_1 = 1
}

enum EQUIPMENT_TYPE : ubyte
{
    WEAPON = 0,
    ARMOR = 1
}

enum NON_TARGET_TYPE : ubyte
{
    PRIEST_PROJ = 0,
    GOBLIN_PROJ = 1,
    BOSS_PROJ_1 = 2,
    BOSS_PROJ_2 = 3
}

enum BOSS_FLY_TYPE : ubyte
{
    BOSS_FLY_TYPE_1 = 0,
    BOSS_FLY_TYPE_2 = 1
}

enum BOSS_MOVE_TYPE : ubyte
{
    BOSS_MOVE_TYPE_1 = 0,
    BOSS_MOVE_TYPE_2 = 1
}