// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_NAGOX_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_NAGOX_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 24,
             "Non-compatible flatbuffers version included");

#include "enum_generated.h"
#include "struct_generated.h"

namespace Nagox {
namespace Protocol {

struct c2s_LOGIN;
struct c2s_LOGINBuilder;

struct s2c_LOGIN;
struct s2c_LOGINBuilder;

struct c2s_PING_PONG;
struct c2s_PING_PONGBuilder;

struct s2c_PING_PONG;
struct s2c_PING_PONGBuilder;

struct c2s_ENTER;
struct c2s_ENTERBuilder;

struct s2c_APPEAR_OBJECT;
struct s2c_APPEAR_OBJECTBuilder;

struct s2c_REMOVE_OBJECT;
struct s2c_REMOVE_OBJECTBuilder;

struct c2s_MOVE;
struct c2s_MOVEBuilder;

struct s2c_MOVE;
struct s2c_MOVEBuilder;

struct s2c_MONSTER_ATTACK;
struct s2c_MONSTER_ATTACKBuilder;

struct s2c_NOTIFY_HIT_DMG;
struct s2c_NOTIFY_HIT_DMGBuilder;

struct s2c_MONSTER_AGGRO_START;
struct s2c_MONSTER_AGGRO_STARTBuilder;

struct s2c_MONSTER_AGGRO_END;
struct s2c_MONSTER_AGGRO_ENDBuilder;

struct c2s_PLAYER_ATTACK;
struct c2s_PLAYER_ATTACKBuilder;

struct s2c_PLAYER_ATTACK;
struct s2c_PLAYER_ATTACKBuilder;

struct s2c_PLAYER_DEATH;
struct s2c_PLAYER_DEATHBuilder;

struct c2s_PLAYER_DEATH;
struct c2s_PLAYER_DEATHBuilder;

struct c2s_REQUEST_QUEST;
struct c2s_REQUEST_QUESTBuilder;

struct s2c_REQUEST_QUEST;
struct s2c_REQUEST_QUESTBuilder;

struct s2c_CLEAR_QUEST;
struct s2c_CLEAR_QUESTBuilder;

struct c2s_FIRE_PROJ;
struct c2s_FIRE_PROJBuilder;

struct s2c_FIRE_PROJ;
struct s2c_FIRE_PROJBuilder;

struct c2s_ACQUIRE_ITEM;
struct c2s_ACQUIRE_ITEMBuilder;

struct s2c_ACQUIRE_ITEM;
struct s2c_ACQUIRE_ITEMBuilder;

struct c2s_REQUEST_QUICK_SLOT;
struct c2s_REQUEST_QUICK_SLOTBuilder;

struct c2s_USE_QUICK_SLOT_ITEM;
struct c2s_USE_QUICK_SLOT_ITEMBuilder;

struct s2c_USE_QUICK_SLOT_ITEM;
struct s2c_USE_QUICK_SLOT_ITEMBuilder;

struct c2s_CRAFT_ITEM;
struct c2s_CRAFT_ITEMBuilder;

struct s2c_CRAFT_ITEM;
struct s2c_CRAFT_ITEMBuilder;

struct c2s_REGISTER_PARTY_QUEST;
struct c2s_REGISTER_PARTY_QUESTBuilder;

struct s2c_REGISTER_PARTY_QUEST;
struct s2c_REGISTER_PARTY_QUESTBuilder;

struct c2s_ACQUIRE_PARTY_LIST;
struct c2s_ACQUIRE_PARTY_LISTBuilder;

struct s2c_ACQUIRE_PARTY_LIST;
struct s2c_ACQUIRE_PARTY_LISTBuilder;

struct c2s_INVITE_PARTY_QUEST;
struct c2s_INVITE_PARTY_QUESTBuilder;

struct s2c_INVITE_PARTY_QUEST;
struct s2c_INVITE_PARTY_QUESTBuilder;

struct c2s_INVITE_PARTY_RESULT;
struct c2s_INVITE_PARTY_RESULTBuilder;

struct s2c_INVITE_PARTY_RESULT;
struct s2c_INVITE_PARTY_RESULTBuilder;

struct c2s_PARTY_JOIN_REQUEST;
struct c2s_PARTY_JOIN_REQUESTBuilder;

struct s2c_PARTY_JOIN_REQUEST;
struct s2c_PARTY_JOIN_REQUESTBuilder;

struct c2s_PARTY_JOIN_REQUEST_RESULT;
struct c2s_PARTY_JOIN_REQUEST_RESULTBuilder;

struct s2c_PARTY_JOIN_REQUEST_RESULT;
struct s2c_PARTY_JOIN_REQUEST_RESULTBuilder;

struct s2c_PARTY_JOIN_NEW_PLAYER;
struct s2c_PARTY_JOIN_NEW_PLAYERBuilder;

struct c2s_QUEST_START;
struct c2s_QUEST_STARTBuilder;

struct c2s_QUEST_END;
struct c2s_QUEST_ENDBuilder;

struct c2s_PARTY_OUT;
struct c2s_PARTY_OUTBuilder;

struct s2c_PARTY_OUT;
struct s2c_PARTY_OUTBuilder;

struct s2c_PARTY_QUEST_CLEAR;
struct s2c_PARTY_QUEST_CLEARBuilder;

struct s2c_PARTY_MEMBERS_INFORMATION;
struct s2c_PARTY_MEMBERS_INFORMATIONBuilder;

struct c2s_LOGIN FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_LOGINBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct c2s_LOGINBuilder {
  typedef c2s_LOGIN Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(c2s_LOGIN::VT_NAME, name);
  }
  explicit c2s_LOGINBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_LOGIN> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_LOGIN>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_LOGIN> Createc2s_LOGIN(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  c2s_LOGINBuilder builder_(_fbb);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<c2s_LOGIN> Createc2s_LOGINDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Nagox::Protocol::Createc2s_LOGIN(
      _fbb,
      name__);
}

struct s2c_LOGIN FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_LOGINBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ_ID = 4,
    VT_SERVER_TIME_STAMP = 6
  };
  uint32_t obj_id() const {
    return GetField<uint32_t>(VT_OBJ_ID, 0);
  }
  bool mutate_obj_id(uint32_t _obj_id = 0) {
    return SetField<uint32_t>(VT_OBJ_ID, _obj_id, 0);
  }
  uint64_t server_time_stamp() const {
    return GetField<uint64_t>(VT_SERVER_TIME_STAMP, 0);
  }
  bool mutate_server_time_stamp(uint64_t _server_time_stamp = 0) {
    return SetField<uint64_t>(VT_SERVER_TIME_STAMP, _server_time_stamp, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_OBJ_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIME_STAMP, 8) &&
           verifier.EndTable();
  }
};

struct s2c_LOGINBuilder {
  typedef s2c_LOGIN Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj_id(uint32_t obj_id) {
    fbb_.AddElement<uint32_t>(s2c_LOGIN::VT_OBJ_ID, obj_id, 0);
  }
  void add_server_time_stamp(uint64_t server_time_stamp) {
    fbb_.AddElement<uint64_t>(s2c_LOGIN::VT_SERVER_TIME_STAMP, server_time_stamp, 0);
  }
  explicit s2c_LOGINBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_LOGIN> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_LOGIN>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_LOGIN> Creates2c_LOGIN(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t obj_id = 0,
    uint64_t server_time_stamp = 0) {
  s2c_LOGINBuilder builder_(_fbb);
  builder_.add_server_time_stamp(server_time_stamp);
  builder_.add_obj_id(obj_id);
  return builder_.Finish();
}

struct c2s_PING_PONG FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_PING_PONGBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct c2s_PING_PONGBuilder {
  typedef c2s_PING_PONG Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit c2s_PING_PONGBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_PING_PONG> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_PING_PONG>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_PING_PONG> Createc2s_PING_PONG(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  c2s_PING_PONGBuilder builder_(_fbb);
  return builder_.Finish();
}

struct s2c_PING_PONG FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_PING_PONGBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVER_TIME_STAMP = 4
  };
  uint64_t server_time_stamp() const {
    return GetField<uint64_t>(VT_SERVER_TIME_STAMP, 0);
  }
  bool mutate_server_time_stamp(uint64_t _server_time_stamp = 0) {
    return SetField<uint64_t>(VT_SERVER_TIME_STAMP, _server_time_stamp, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIME_STAMP, 8) &&
           verifier.EndTable();
  }
};

struct s2c_PING_PONGBuilder {
  typedef s2c_PING_PONG Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_server_time_stamp(uint64_t server_time_stamp) {
    fbb_.AddElement<uint64_t>(s2c_PING_PONG::VT_SERVER_TIME_STAMP, server_time_stamp, 0);
  }
  explicit s2c_PING_PONGBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_PING_PONG> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_PING_PONG>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_PING_PONG> Creates2c_PING_PONG(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t server_time_stamp = 0) {
  s2c_PING_PONGBuilder builder_(_fbb);
  builder_.add_server_time_stamp(server_time_stamp);
  return builder_.Finish();
}

struct c2s_ENTER FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_ENTERBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4
  };
  const Nagox::Struct::Vec3 *pos() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_POS);
  }
  Nagox::Struct::Vec3 *mutable_pos() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_POS, 4) &&
           verifier.EndTable();
  }
};

struct c2s_ENTERBuilder {
  typedef c2s_ENTER Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pos(const Nagox::Struct::Vec3 *pos) {
    fbb_.AddStruct(c2s_ENTER::VT_POS, pos);
  }
  explicit c2s_ENTERBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_ENTER> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_ENTER>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_ENTER> Createc2s_ENTER(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Nagox::Struct::Vec3 *pos = nullptr) {
  c2s_ENTERBuilder builder_(_fbb);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct s2c_APPEAR_OBJECT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_APPEAR_OBJECTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ_ID = 4,
    VT_GROUP_TYPE = 6,
    VT_OBJ_TYPE_INFO = 8,
    VT_APPEAR_POS = 10,
    VT_OBJ_MAX_HP = 12,
    VT_OBJ_CUR_HP = 14
  };
  uint32_t obj_id() const {
    return GetField<uint32_t>(VT_OBJ_ID, 0);
  }
  bool mutate_obj_id(uint32_t _obj_id = 0) {
    return SetField<uint32_t>(VT_OBJ_ID, _obj_id, 0);
  }
  Nagox::Enum::GROUP_TYPE group_type() const {
    return static_cast<Nagox::Enum::GROUP_TYPE>(GetField<uint8_t>(VT_GROUP_TYPE, 0));
  }
  bool mutate_group_type(Nagox::Enum::GROUP_TYPE _group_type = static_cast<Nagox::Enum::GROUP_TYPE>(0)) {
    return SetField<uint8_t>(VT_GROUP_TYPE, static_cast<uint8_t>(_group_type), 0);
  }
  uint8_t obj_type_info() const {
    return GetField<uint8_t>(VT_OBJ_TYPE_INFO, 0);
  }
  bool mutate_obj_type_info(uint8_t _obj_type_info = 0) {
    return SetField<uint8_t>(VT_OBJ_TYPE_INFO, _obj_type_info, 0);
  }
  const Nagox::Struct::Vec3 *appear_pos() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_APPEAR_POS);
  }
  Nagox::Struct::Vec3 *mutable_appear_pos() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_APPEAR_POS);
  }
  int32_t obj_max_hp() const {
    return GetField<int32_t>(VT_OBJ_MAX_HP, 0);
  }
  bool mutate_obj_max_hp(int32_t _obj_max_hp = 0) {
    return SetField<int32_t>(VT_OBJ_MAX_HP, _obj_max_hp, 0);
  }
  int32_t obj_cur_hp() const {
    return GetField<int32_t>(VT_OBJ_CUR_HP, 0);
  }
  bool mutate_obj_cur_hp(int32_t _obj_cur_hp = 0) {
    return SetField<int32_t>(VT_OBJ_CUR_HP, _obj_cur_hp, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_OBJ_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_GROUP_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_OBJ_TYPE_INFO, 1) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_APPEAR_POS, 4) &&
           VerifyField<int32_t>(verifier, VT_OBJ_MAX_HP, 4) &&
           VerifyField<int32_t>(verifier, VT_OBJ_CUR_HP, 4) &&
           verifier.EndTable();
  }
};

struct s2c_APPEAR_OBJECTBuilder {
  typedef s2c_APPEAR_OBJECT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj_id(uint32_t obj_id) {
    fbb_.AddElement<uint32_t>(s2c_APPEAR_OBJECT::VT_OBJ_ID, obj_id, 0);
  }
  void add_group_type(Nagox::Enum::GROUP_TYPE group_type) {
    fbb_.AddElement<uint8_t>(s2c_APPEAR_OBJECT::VT_GROUP_TYPE, static_cast<uint8_t>(group_type), 0);
  }
  void add_obj_type_info(uint8_t obj_type_info) {
    fbb_.AddElement<uint8_t>(s2c_APPEAR_OBJECT::VT_OBJ_TYPE_INFO, obj_type_info, 0);
  }
  void add_appear_pos(const Nagox::Struct::Vec3 *appear_pos) {
    fbb_.AddStruct(s2c_APPEAR_OBJECT::VT_APPEAR_POS, appear_pos);
  }
  void add_obj_max_hp(int32_t obj_max_hp) {
    fbb_.AddElement<int32_t>(s2c_APPEAR_OBJECT::VT_OBJ_MAX_HP, obj_max_hp, 0);
  }
  void add_obj_cur_hp(int32_t obj_cur_hp) {
    fbb_.AddElement<int32_t>(s2c_APPEAR_OBJECT::VT_OBJ_CUR_HP, obj_cur_hp, 0);
  }
  explicit s2c_APPEAR_OBJECTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_APPEAR_OBJECT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_APPEAR_OBJECT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_APPEAR_OBJECT> Creates2c_APPEAR_OBJECT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t obj_id = 0,
    Nagox::Enum::GROUP_TYPE group_type = Nagox::Enum::GROUP_TYPE_PLAYER,
    uint8_t obj_type_info = 0,
    const Nagox::Struct::Vec3 *appear_pos = nullptr,
    int32_t obj_max_hp = 0,
    int32_t obj_cur_hp = 0) {
  s2c_APPEAR_OBJECTBuilder builder_(_fbb);
  builder_.add_obj_cur_hp(obj_cur_hp);
  builder_.add_obj_max_hp(obj_max_hp);
  builder_.add_appear_pos(appear_pos);
  builder_.add_obj_id(obj_id);
  builder_.add_obj_type_info(obj_type_info);
  builder_.add_group_type(group_type);
  return builder_.Finish();
}

struct s2c_REMOVE_OBJECT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_REMOVE_OBJECTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ_ID = 4
  };
  uint32_t obj_id() const {
    return GetField<uint32_t>(VT_OBJ_ID, 0);
  }
  bool mutate_obj_id(uint32_t _obj_id = 0) {
    return SetField<uint32_t>(VT_OBJ_ID, _obj_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_OBJ_ID, 4) &&
           verifier.EndTable();
  }
};

struct s2c_REMOVE_OBJECTBuilder {
  typedef s2c_REMOVE_OBJECT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj_id(uint32_t obj_id) {
    fbb_.AddElement<uint32_t>(s2c_REMOVE_OBJECT::VT_OBJ_ID, obj_id, 0);
  }
  explicit s2c_REMOVE_OBJECTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_REMOVE_OBJECT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_REMOVE_OBJECT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_REMOVE_OBJECT> Creates2c_REMOVE_OBJECT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t obj_id = 0) {
  s2c_REMOVE_OBJECTBuilder builder_(_fbb);
  builder_.add_obj_id(obj_id);
  return builder_.Finish();
}

struct c2s_MOVE FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_MOVEBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4,
    VT_VEL = 6,
    VT_ACCEL = 8,
    VT_BODY_ANGLE = 10,
    VT_TIME_STAMP = 12
  };
  const Nagox::Struct::Vec3 *pos() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_POS);
  }
  Nagox::Struct::Vec3 *mutable_pos() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_POS);
  }
  const Nagox::Struct::Vec3 *vel() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_VEL);
  }
  Nagox::Struct::Vec3 *mutable_vel() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_VEL);
  }
  const Nagox::Struct::Vec3 *accel() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_ACCEL);
  }
  Nagox::Struct::Vec3 *mutable_accel() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_ACCEL);
  }
  float body_angle() const {
    return GetField<float>(VT_BODY_ANGLE, 0.0f);
  }
  bool mutate_body_angle(float _body_angle = 0.0f) {
    return SetField<float>(VT_BODY_ANGLE, _body_angle, 0.0f);
  }
  uint64_t time_stamp() const {
    return GetField<uint64_t>(VT_TIME_STAMP, 0);
  }
  bool mutate_time_stamp(uint64_t _time_stamp = 0) {
    return SetField<uint64_t>(VT_TIME_STAMP, _time_stamp, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_POS, 4) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_VEL, 4) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_ACCEL, 4) &&
           VerifyField<float>(verifier, VT_BODY_ANGLE, 4) &&
           VerifyField<uint64_t>(verifier, VT_TIME_STAMP, 8) &&
           verifier.EndTable();
  }
};

struct c2s_MOVEBuilder {
  typedef c2s_MOVE Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pos(const Nagox::Struct::Vec3 *pos) {
    fbb_.AddStruct(c2s_MOVE::VT_POS, pos);
  }
  void add_vel(const Nagox::Struct::Vec3 *vel) {
    fbb_.AddStruct(c2s_MOVE::VT_VEL, vel);
  }
  void add_accel(const Nagox::Struct::Vec3 *accel) {
    fbb_.AddStruct(c2s_MOVE::VT_ACCEL, accel);
  }
  void add_body_angle(float body_angle) {
    fbb_.AddElement<float>(c2s_MOVE::VT_BODY_ANGLE, body_angle, 0.0f);
  }
  void add_time_stamp(uint64_t time_stamp) {
    fbb_.AddElement<uint64_t>(c2s_MOVE::VT_TIME_STAMP, time_stamp, 0);
  }
  explicit c2s_MOVEBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_MOVE> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_MOVE>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_MOVE> Createc2s_MOVE(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Nagox::Struct::Vec3 *pos = nullptr,
    const Nagox::Struct::Vec3 *vel = nullptr,
    const Nagox::Struct::Vec3 *accel = nullptr,
    float body_angle = 0.0f,
    uint64_t time_stamp = 0) {
  c2s_MOVEBuilder builder_(_fbb);
  builder_.add_time_stamp(time_stamp);
  builder_.add_body_angle(body_angle);
  builder_.add_accel(accel);
  builder_.add_vel(vel);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct s2c_MOVE FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_MOVEBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ_ID = 4,
    VT_POS = 6,
    VT_VEL = 8,
    VT_ACCEL = 10,
    VT_BODY_ANGLE = 12,
    VT_TIME_STAMP = 14
  };
  uint64_t obj_id() const {
    return GetField<uint64_t>(VT_OBJ_ID, 0);
  }
  bool mutate_obj_id(uint64_t _obj_id = 0) {
    return SetField<uint64_t>(VT_OBJ_ID, _obj_id, 0);
  }
  const Nagox::Struct::Vec3 *pos() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_POS);
  }
  Nagox::Struct::Vec3 *mutable_pos() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_POS);
  }
  const Nagox::Struct::Vec3 *vel() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_VEL);
  }
  Nagox::Struct::Vec3 *mutable_vel() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_VEL);
  }
  const Nagox::Struct::Vec3 *accel() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_ACCEL);
  }
  Nagox::Struct::Vec3 *mutable_accel() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_ACCEL);
  }
  float body_angle() const {
    return GetField<float>(VT_BODY_ANGLE, 0.0f);
  }
  bool mutate_body_angle(float _body_angle = 0.0f) {
    return SetField<float>(VT_BODY_ANGLE, _body_angle, 0.0f);
  }
  uint64_t time_stamp() const {
    return GetField<uint64_t>(VT_TIME_STAMP, 0);
  }
  bool mutate_time_stamp(uint64_t _time_stamp = 0) {
    return SetField<uint64_t>(VT_TIME_STAMP, _time_stamp, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJ_ID, 8) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_POS, 4) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_VEL, 4) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_ACCEL, 4) &&
           VerifyField<float>(verifier, VT_BODY_ANGLE, 4) &&
           VerifyField<uint64_t>(verifier, VT_TIME_STAMP, 8) &&
           verifier.EndTable();
  }
};

struct s2c_MOVEBuilder {
  typedef s2c_MOVE Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj_id(uint64_t obj_id) {
    fbb_.AddElement<uint64_t>(s2c_MOVE::VT_OBJ_ID, obj_id, 0);
  }
  void add_pos(const Nagox::Struct::Vec3 *pos) {
    fbb_.AddStruct(s2c_MOVE::VT_POS, pos);
  }
  void add_vel(const Nagox::Struct::Vec3 *vel) {
    fbb_.AddStruct(s2c_MOVE::VT_VEL, vel);
  }
  void add_accel(const Nagox::Struct::Vec3 *accel) {
    fbb_.AddStruct(s2c_MOVE::VT_ACCEL, accel);
  }
  void add_body_angle(float body_angle) {
    fbb_.AddElement<float>(s2c_MOVE::VT_BODY_ANGLE, body_angle, 0.0f);
  }
  void add_time_stamp(uint64_t time_stamp) {
    fbb_.AddElement<uint64_t>(s2c_MOVE::VT_TIME_STAMP, time_stamp, 0);
  }
  explicit s2c_MOVEBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_MOVE> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_MOVE>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_MOVE> Creates2c_MOVE(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t obj_id = 0,
    const Nagox::Struct::Vec3 *pos = nullptr,
    const Nagox::Struct::Vec3 *vel = nullptr,
    const Nagox::Struct::Vec3 *accel = nullptr,
    float body_angle = 0.0f,
    uint64_t time_stamp = 0) {
  s2c_MOVEBuilder builder_(_fbb);
  builder_.add_time_stamp(time_stamp);
  builder_.add_obj_id(obj_id);
  builder_.add_body_angle(body_angle);
  builder_.add_accel(accel);
  builder_.add_vel(vel);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct s2c_MONSTER_ATTACK FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_MONSTER_ATTACKBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ_ID = 4,
    VT_PLAYER_ID = 6,
    VT_DMG = 8
  };
  uint64_t obj_id() const {
    return GetField<uint64_t>(VT_OBJ_ID, 0);
  }
  bool mutate_obj_id(uint64_t _obj_id = 0) {
    return SetField<uint64_t>(VT_OBJ_ID, _obj_id, 0);
  }
  uint64_t player_id() const {
    return GetField<uint64_t>(VT_PLAYER_ID, 0);
  }
  bool mutate_player_id(uint64_t _player_id = 0) {
    return SetField<uint64_t>(VT_PLAYER_ID, _player_id, 0);
  }
  uint32_t dmg() const {
    return GetField<uint32_t>(VT_DMG, 0);
  }
  bool mutate_dmg(uint32_t _dmg = 0) {
    return SetField<uint32_t>(VT_DMG, _dmg, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OBJ_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_PLAYER_ID, 8) &&
           VerifyField<uint32_t>(verifier, VT_DMG, 4) &&
           verifier.EndTable();
  }
};

struct s2c_MONSTER_ATTACKBuilder {
  typedef s2c_MONSTER_ATTACK Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj_id(uint64_t obj_id) {
    fbb_.AddElement<uint64_t>(s2c_MONSTER_ATTACK::VT_OBJ_ID, obj_id, 0);
  }
  void add_player_id(uint64_t player_id) {
    fbb_.AddElement<uint64_t>(s2c_MONSTER_ATTACK::VT_PLAYER_ID, player_id, 0);
  }
  void add_dmg(uint32_t dmg) {
    fbb_.AddElement<uint32_t>(s2c_MONSTER_ATTACK::VT_DMG, dmg, 0);
  }
  explicit s2c_MONSTER_ATTACKBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_MONSTER_ATTACK> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_MONSTER_ATTACK>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_MONSTER_ATTACK> Creates2c_MONSTER_ATTACK(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t obj_id = 0,
    uint64_t player_id = 0,
    uint32_t dmg = 0) {
  s2c_MONSTER_ATTACKBuilder builder_(_fbb);
  builder_.add_player_id(player_id);
  builder_.add_obj_id(obj_id);
  builder_.add_dmg(dmg);
  return builder_.Finish();
}

struct s2c_NOTIFY_HIT_DMG FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_NOTIFY_HIT_DMGBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HIT_OBJ_ID = 4,
    VT_HIT_AFTER_HP = 6
  };
  uint64_t hit_obj_id() const {
    return GetField<uint64_t>(VT_HIT_OBJ_ID, 0);
  }
  bool mutate_hit_obj_id(uint64_t _hit_obj_id = 0) {
    return SetField<uint64_t>(VT_HIT_OBJ_ID, _hit_obj_id, 0);
  }
  int32_t hit_after_hp() const {
    return GetField<int32_t>(VT_HIT_AFTER_HP, 0);
  }
  bool mutate_hit_after_hp(int32_t _hit_after_hp = 0) {
    return SetField<int32_t>(VT_HIT_AFTER_HP, _hit_after_hp, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_HIT_OBJ_ID, 8) &&
           VerifyField<int32_t>(verifier, VT_HIT_AFTER_HP, 4) &&
           verifier.EndTable();
  }
};

struct s2c_NOTIFY_HIT_DMGBuilder {
  typedef s2c_NOTIFY_HIT_DMG Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_hit_obj_id(uint64_t hit_obj_id) {
    fbb_.AddElement<uint64_t>(s2c_NOTIFY_HIT_DMG::VT_HIT_OBJ_ID, hit_obj_id, 0);
  }
  void add_hit_after_hp(int32_t hit_after_hp) {
    fbb_.AddElement<int32_t>(s2c_NOTIFY_HIT_DMG::VT_HIT_AFTER_HP, hit_after_hp, 0);
  }
  explicit s2c_NOTIFY_HIT_DMGBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_NOTIFY_HIT_DMG> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_NOTIFY_HIT_DMG>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_NOTIFY_HIT_DMG> Creates2c_NOTIFY_HIT_DMG(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t hit_obj_id = 0,
    int32_t hit_after_hp = 0) {
  s2c_NOTIFY_HIT_DMGBuilder builder_(_fbb);
  builder_.add_hit_obj_id(hit_obj_id);
  builder_.add_hit_after_hp(hit_after_hp);
  return builder_.Finish();
}

struct s2c_MONSTER_AGGRO_START FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_MONSTER_AGGRO_STARTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GROUP_TYPE = 4,
    VT_OBJ_TYPE_INFO = 6
  };
  Nagox::Enum::GROUP_TYPE group_type() const {
    return static_cast<Nagox::Enum::GROUP_TYPE>(GetField<uint8_t>(VT_GROUP_TYPE, 0));
  }
  bool mutate_group_type(Nagox::Enum::GROUP_TYPE _group_type = static_cast<Nagox::Enum::GROUP_TYPE>(0)) {
    return SetField<uint8_t>(VT_GROUP_TYPE, static_cast<uint8_t>(_group_type), 0);
  }
  uint8_t obj_type_info() const {
    return GetField<uint8_t>(VT_OBJ_TYPE_INFO, 0);
  }
  bool mutate_obj_type_info(uint8_t _obj_type_info = 0) {
    return SetField<uint8_t>(VT_OBJ_TYPE_INFO, _obj_type_info, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_GROUP_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_OBJ_TYPE_INFO, 1) &&
           verifier.EndTable();
  }
};

struct s2c_MONSTER_AGGRO_STARTBuilder {
  typedef s2c_MONSTER_AGGRO_START Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_group_type(Nagox::Enum::GROUP_TYPE group_type) {
    fbb_.AddElement<uint8_t>(s2c_MONSTER_AGGRO_START::VT_GROUP_TYPE, static_cast<uint8_t>(group_type), 0);
  }
  void add_obj_type_info(uint8_t obj_type_info) {
    fbb_.AddElement<uint8_t>(s2c_MONSTER_AGGRO_START::VT_OBJ_TYPE_INFO, obj_type_info, 0);
  }
  explicit s2c_MONSTER_AGGRO_STARTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_MONSTER_AGGRO_START> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_MONSTER_AGGRO_START>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_MONSTER_AGGRO_START> Creates2c_MONSTER_AGGRO_START(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Nagox::Enum::GROUP_TYPE group_type = Nagox::Enum::GROUP_TYPE_PLAYER,
    uint8_t obj_type_info = 0) {
  s2c_MONSTER_AGGRO_STARTBuilder builder_(_fbb);
  builder_.add_obj_type_info(obj_type_info);
  builder_.add_group_type(group_type);
  return builder_.Finish();
}

struct s2c_MONSTER_AGGRO_END FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_MONSTER_AGGRO_ENDBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GROUP_TYPE = 4,
    VT_OBJ_TYPE_INFO = 6
  };
  Nagox::Enum::GROUP_TYPE group_type() const {
    return static_cast<Nagox::Enum::GROUP_TYPE>(GetField<uint8_t>(VT_GROUP_TYPE, 0));
  }
  bool mutate_group_type(Nagox::Enum::GROUP_TYPE _group_type = static_cast<Nagox::Enum::GROUP_TYPE>(0)) {
    return SetField<uint8_t>(VT_GROUP_TYPE, static_cast<uint8_t>(_group_type), 0);
  }
  uint8_t obj_type_info() const {
    return GetField<uint8_t>(VT_OBJ_TYPE_INFO, 0);
  }
  bool mutate_obj_type_info(uint8_t _obj_type_info = 0) {
    return SetField<uint8_t>(VT_OBJ_TYPE_INFO, _obj_type_info, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_GROUP_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_OBJ_TYPE_INFO, 1) &&
           verifier.EndTable();
  }
};

struct s2c_MONSTER_AGGRO_ENDBuilder {
  typedef s2c_MONSTER_AGGRO_END Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_group_type(Nagox::Enum::GROUP_TYPE group_type) {
    fbb_.AddElement<uint8_t>(s2c_MONSTER_AGGRO_END::VT_GROUP_TYPE, static_cast<uint8_t>(group_type), 0);
  }
  void add_obj_type_info(uint8_t obj_type_info) {
    fbb_.AddElement<uint8_t>(s2c_MONSTER_AGGRO_END::VT_OBJ_TYPE_INFO, obj_type_info, 0);
  }
  explicit s2c_MONSTER_AGGRO_ENDBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_MONSTER_AGGRO_END> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_MONSTER_AGGRO_END>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_MONSTER_AGGRO_END> Creates2c_MONSTER_AGGRO_END(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Nagox::Enum::GROUP_TYPE group_type = Nagox::Enum::GROUP_TYPE_PLAYER,
    uint8_t obj_type_info = 0) {
  s2c_MONSTER_AGGRO_ENDBuilder builder_(_fbb);
  builder_.add_obj_type_info(obj_type_info);
  builder_.add_group_type(group_type);
  return builder_.Finish();
}

struct c2s_PLAYER_ATTACK FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_PLAYER_ATTACKBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_ANGLE = 4,
    VT_ATK_POS = 6
  };
  float body_angle() const {
    return GetField<float>(VT_BODY_ANGLE, 0.0f);
  }
  bool mutate_body_angle(float _body_angle = 0.0f) {
    return SetField<float>(VT_BODY_ANGLE, _body_angle, 0.0f);
  }
  const Nagox::Struct::Vec3 *atk_pos() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_ATK_POS);
  }
  Nagox::Struct::Vec3 *mutable_atk_pos() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_ATK_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_BODY_ANGLE, 4) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_ATK_POS, 4) &&
           verifier.EndTable();
  }
};

struct c2s_PLAYER_ATTACKBuilder {
  typedef c2s_PLAYER_ATTACK Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_angle(float body_angle) {
    fbb_.AddElement<float>(c2s_PLAYER_ATTACK::VT_BODY_ANGLE, body_angle, 0.0f);
  }
  void add_atk_pos(const Nagox::Struct::Vec3 *atk_pos) {
    fbb_.AddStruct(c2s_PLAYER_ATTACK::VT_ATK_POS, atk_pos);
  }
  explicit c2s_PLAYER_ATTACKBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_PLAYER_ATTACK> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_PLAYER_ATTACK>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_PLAYER_ATTACK> Createc2s_PLAYER_ATTACK(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float body_angle = 0.0f,
    const Nagox::Struct::Vec3 *atk_pos = nullptr) {
  c2s_PLAYER_ATTACKBuilder builder_(_fbb);
  builder_.add_atk_pos(atk_pos);
  builder_.add_body_angle(body_angle);
  return builder_.Finish();
}

struct s2c_PLAYER_ATTACK FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_PLAYER_ATTACKBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ATK_PLAYER_ID = 4,
    VT_BODY_ANGLE = 6,
    VT_ATK_POS = 8
  };
  uint64_t atk_player_id() const {
    return GetField<uint64_t>(VT_ATK_PLAYER_ID, 0);
  }
  bool mutate_atk_player_id(uint64_t _atk_player_id = 0) {
    return SetField<uint64_t>(VT_ATK_PLAYER_ID, _atk_player_id, 0);
  }
  float body_angle() const {
    return GetField<float>(VT_BODY_ANGLE, 0.0f);
  }
  bool mutate_body_angle(float _body_angle = 0.0f) {
    return SetField<float>(VT_BODY_ANGLE, _body_angle, 0.0f);
  }
  const Nagox::Struct::Vec3 *atk_pos() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_ATK_POS);
  }
  Nagox::Struct::Vec3 *mutable_atk_pos() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_ATK_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ATK_PLAYER_ID, 8) &&
           VerifyField<float>(verifier, VT_BODY_ANGLE, 4) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_ATK_POS, 4) &&
           verifier.EndTable();
  }
};

struct s2c_PLAYER_ATTACKBuilder {
  typedef s2c_PLAYER_ATTACK Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_atk_player_id(uint64_t atk_player_id) {
    fbb_.AddElement<uint64_t>(s2c_PLAYER_ATTACK::VT_ATK_PLAYER_ID, atk_player_id, 0);
  }
  void add_body_angle(float body_angle) {
    fbb_.AddElement<float>(s2c_PLAYER_ATTACK::VT_BODY_ANGLE, body_angle, 0.0f);
  }
  void add_atk_pos(const Nagox::Struct::Vec3 *atk_pos) {
    fbb_.AddStruct(s2c_PLAYER_ATTACK::VT_ATK_POS, atk_pos);
  }
  explicit s2c_PLAYER_ATTACKBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_PLAYER_ATTACK> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_PLAYER_ATTACK>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_PLAYER_ATTACK> Creates2c_PLAYER_ATTACK(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t atk_player_id = 0,
    float body_angle = 0.0f,
    const Nagox::Struct::Vec3 *atk_pos = nullptr) {
  s2c_PLAYER_ATTACKBuilder builder_(_fbb);
  builder_.add_atk_player_id(atk_player_id);
  builder_.add_atk_pos(atk_pos);
  builder_.add_body_angle(body_angle);
  return builder_.Finish();
}

struct s2c_PLAYER_DEATH FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_PLAYER_DEATHBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_REBIRTH_POS = 6
  };
  uint64_t player_id() const {
    return GetField<uint64_t>(VT_PLAYER_ID, 0);
  }
  bool mutate_player_id(uint64_t _player_id = 0) {
    return SetField<uint64_t>(VT_PLAYER_ID, _player_id, 0);
  }
  const Nagox::Struct::Vec3 *rebirth_pos() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_REBIRTH_POS);
  }
  Nagox::Struct::Vec3 *mutable_rebirth_pos() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_REBIRTH_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_PLAYER_ID, 8) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_REBIRTH_POS, 4) &&
           verifier.EndTable();
  }
};

struct s2c_PLAYER_DEATHBuilder {
  typedef s2c_PLAYER_DEATH Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint64_t player_id) {
    fbb_.AddElement<uint64_t>(s2c_PLAYER_DEATH::VT_PLAYER_ID, player_id, 0);
  }
  void add_rebirth_pos(const Nagox::Struct::Vec3 *rebirth_pos) {
    fbb_.AddStruct(s2c_PLAYER_DEATH::VT_REBIRTH_POS, rebirth_pos);
  }
  explicit s2c_PLAYER_DEATHBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_PLAYER_DEATH> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_PLAYER_DEATH>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_PLAYER_DEATH> Creates2c_PLAYER_DEATH(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t player_id = 0,
    const Nagox::Struct::Vec3 *rebirth_pos = nullptr) {
  s2c_PLAYER_DEATHBuilder builder_(_fbb);
  builder_.add_player_id(player_id);
  builder_.add_rebirth_pos(rebirth_pos);
  return builder_.Finish();
}

struct c2s_PLAYER_DEATH FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_PLAYER_DEATHBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct c2s_PLAYER_DEATHBuilder {
  typedef c2s_PLAYER_DEATH Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit c2s_PLAYER_DEATHBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_PLAYER_DEATH> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_PLAYER_DEATH>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_PLAYER_DEATH> Createc2s_PLAYER_DEATH(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  c2s_PLAYER_DEATHBuilder builder_(_fbb);
  return builder_.Finish();
}

struct c2s_REQUEST_QUEST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_REQUEST_QUESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUEST_ID = 4
  };
  uint64_t quest_id() const {
    return GetField<uint64_t>(VT_QUEST_ID, 0);
  }
  bool mutate_quest_id(uint64_t _quest_id = 0) {
    return SetField<uint64_t>(VT_QUEST_ID, _quest_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_QUEST_ID, 8) &&
           verifier.EndTable();
  }
};

struct c2s_REQUEST_QUESTBuilder {
  typedef c2s_REQUEST_QUEST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_quest_id(uint64_t quest_id) {
    fbb_.AddElement<uint64_t>(c2s_REQUEST_QUEST::VT_QUEST_ID, quest_id, 0);
  }
  explicit c2s_REQUEST_QUESTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_REQUEST_QUEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_REQUEST_QUEST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_REQUEST_QUEST> Createc2s_REQUEST_QUEST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t quest_id = 0) {
  c2s_REQUEST_QUESTBuilder builder_(_fbb);
  builder_.add_quest_id(quest_id);
  return builder_.Finish();
}

struct s2c_REQUEST_QUEST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_REQUEST_QUESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUEST_ID = 4
  };
  uint64_t quest_id() const {
    return GetField<uint64_t>(VT_QUEST_ID, 0);
  }
  bool mutate_quest_id(uint64_t _quest_id = 0) {
    return SetField<uint64_t>(VT_QUEST_ID, _quest_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_QUEST_ID, 8) &&
           verifier.EndTable();
  }
};

struct s2c_REQUEST_QUESTBuilder {
  typedef s2c_REQUEST_QUEST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_quest_id(uint64_t quest_id) {
    fbb_.AddElement<uint64_t>(s2c_REQUEST_QUEST::VT_QUEST_ID, quest_id, 0);
  }
  explicit s2c_REQUEST_QUESTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_REQUEST_QUEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_REQUEST_QUEST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_REQUEST_QUEST> Creates2c_REQUEST_QUEST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t quest_id = 0) {
  s2c_REQUEST_QUESTBuilder builder_(_fbb);
  builder_.add_quest_id(quest_id);
  return builder_.Finish();
}

struct s2c_CLEAR_QUEST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_CLEAR_QUESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUEST_ID = 4,
    VT_IS_CLEAR = 6
  };
  uint64_t quest_id() const {
    return GetField<uint64_t>(VT_QUEST_ID, 0);
  }
  bool mutate_quest_id(uint64_t _quest_id = 0) {
    return SetField<uint64_t>(VT_QUEST_ID, _quest_id, 0);
  }
  uint8_t is_clear() const {
    return GetField<uint8_t>(VT_IS_CLEAR, 0);
  }
  bool mutate_is_clear(uint8_t _is_clear = 0) {
    return SetField<uint8_t>(VT_IS_CLEAR, _is_clear, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_QUEST_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_IS_CLEAR, 1) &&
           verifier.EndTable();
  }
};

struct s2c_CLEAR_QUESTBuilder {
  typedef s2c_CLEAR_QUEST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_quest_id(uint64_t quest_id) {
    fbb_.AddElement<uint64_t>(s2c_CLEAR_QUEST::VT_QUEST_ID, quest_id, 0);
  }
  void add_is_clear(uint8_t is_clear) {
    fbb_.AddElement<uint8_t>(s2c_CLEAR_QUEST::VT_IS_CLEAR, is_clear, 0);
  }
  explicit s2c_CLEAR_QUESTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_CLEAR_QUEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_CLEAR_QUEST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_CLEAR_QUEST> Creates2c_CLEAR_QUEST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t quest_id = 0,
    uint8_t is_clear = 0) {
  s2c_CLEAR_QUESTBuilder builder_(_fbb);
  builder_.add_quest_id(quest_id);
  builder_.add_is_clear(is_clear);
  return builder_.Finish();
}

struct c2s_FIRE_PROJ FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_FIRE_PROJBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4,
    VT_BODY_ANGLE = 6
  };
  const Nagox::Struct::Vec3 *pos() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_POS);
  }
  Nagox::Struct::Vec3 *mutable_pos() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_POS);
  }
  float body_angle() const {
    return GetField<float>(VT_BODY_ANGLE, 0.0f);
  }
  bool mutate_body_angle(float _body_angle = 0.0f) {
    return SetField<float>(VT_BODY_ANGLE, _body_angle, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_POS, 4) &&
           VerifyField<float>(verifier, VT_BODY_ANGLE, 4) &&
           verifier.EndTable();
  }
};

struct c2s_FIRE_PROJBuilder {
  typedef c2s_FIRE_PROJ Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pos(const Nagox::Struct::Vec3 *pos) {
    fbb_.AddStruct(c2s_FIRE_PROJ::VT_POS, pos);
  }
  void add_body_angle(float body_angle) {
    fbb_.AddElement<float>(c2s_FIRE_PROJ::VT_BODY_ANGLE, body_angle, 0.0f);
  }
  explicit c2s_FIRE_PROJBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_FIRE_PROJ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_FIRE_PROJ>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_FIRE_PROJ> Createc2s_FIRE_PROJ(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Nagox::Struct::Vec3 *pos = nullptr,
    float body_angle = 0.0f) {
  c2s_FIRE_PROJBuilder builder_(_fbb);
  builder_.add_body_angle(body_angle);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct s2c_FIRE_PROJ FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_FIRE_PROJBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SHOOT_OBJ_ID = 4,
    VT_PROJ_ID = 6,
    VT_PROJ_TYPE = 8,
    VT_POS = 10,
    VT_VEL = 12
  };
  uint64_t shoot_obj_id() const {
    return GetField<uint64_t>(VT_SHOOT_OBJ_ID, 0);
  }
  bool mutate_shoot_obj_id(uint64_t _shoot_obj_id = 0) {
    return SetField<uint64_t>(VT_SHOOT_OBJ_ID, _shoot_obj_id, 0);
  }
  uint64_t proj_id() const {
    return GetField<uint64_t>(VT_PROJ_ID, 0);
  }
  bool mutate_proj_id(uint64_t _proj_id = 0) {
    return SetField<uint64_t>(VT_PROJ_ID, _proj_id, 0);
  }
  uint8_t proj_type() const {
    return GetField<uint8_t>(VT_PROJ_TYPE, 0);
  }
  bool mutate_proj_type(uint8_t _proj_type = 0) {
    return SetField<uint8_t>(VT_PROJ_TYPE, _proj_type, 0);
  }
  const Nagox::Struct::Vec3 *pos() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_POS);
  }
  Nagox::Struct::Vec3 *mutable_pos() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_POS);
  }
  const Nagox::Struct::Vec3 *vel() const {
    return GetStruct<const Nagox::Struct::Vec3 *>(VT_VEL);
  }
  Nagox::Struct::Vec3 *mutable_vel() {
    return GetStruct<Nagox::Struct::Vec3 *>(VT_VEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SHOOT_OBJ_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_PROJ_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_PROJ_TYPE, 1) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_POS, 4) &&
           VerifyField<Nagox::Struct::Vec3>(verifier, VT_VEL, 4) &&
           verifier.EndTable();
  }
};

struct s2c_FIRE_PROJBuilder {
  typedef s2c_FIRE_PROJ Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_shoot_obj_id(uint64_t shoot_obj_id) {
    fbb_.AddElement<uint64_t>(s2c_FIRE_PROJ::VT_SHOOT_OBJ_ID, shoot_obj_id, 0);
  }
  void add_proj_id(uint64_t proj_id) {
    fbb_.AddElement<uint64_t>(s2c_FIRE_PROJ::VT_PROJ_ID, proj_id, 0);
  }
  void add_proj_type(uint8_t proj_type) {
    fbb_.AddElement<uint8_t>(s2c_FIRE_PROJ::VT_PROJ_TYPE, proj_type, 0);
  }
  void add_pos(const Nagox::Struct::Vec3 *pos) {
    fbb_.AddStruct(s2c_FIRE_PROJ::VT_POS, pos);
  }
  void add_vel(const Nagox::Struct::Vec3 *vel) {
    fbb_.AddStruct(s2c_FIRE_PROJ::VT_VEL, vel);
  }
  explicit s2c_FIRE_PROJBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_FIRE_PROJ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_FIRE_PROJ>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_FIRE_PROJ> Creates2c_FIRE_PROJ(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t shoot_obj_id = 0,
    uint64_t proj_id = 0,
    uint8_t proj_type = 0,
    const Nagox::Struct::Vec3 *pos = nullptr,
    const Nagox::Struct::Vec3 *vel = nullptr) {
  s2c_FIRE_PROJBuilder builder_(_fbb);
  builder_.add_proj_id(proj_id);
  builder_.add_shoot_obj_id(shoot_obj_id);
  builder_.add_vel(vel);
  builder_.add_pos(pos);
  builder_.add_proj_type(proj_type);
  return builder_.Finish();
}

struct c2s_ACQUIRE_ITEM FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_ACQUIRE_ITEMBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEM_ID = 4
  };
  uint64_t item_id() const {
    return GetField<uint64_t>(VT_ITEM_ID, 0);
  }
  bool mutate_item_id(uint64_t _item_id = 0) {
    return SetField<uint64_t>(VT_ITEM_ID, _item_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ITEM_ID, 8) &&
           verifier.EndTable();
  }
};

struct c2s_ACQUIRE_ITEMBuilder {
  typedef c2s_ACQUIRE_ITEM Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_item_id(uint64_t item_id) {
    fbb_.AddElement<uint64_t>(c2s_ACQUIRE_ITEM::VT_ITEM_ID, item_id, 0);
  }
  explicit c2s_ACQUIRE_ITEMBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_ACQUIRE_ITEM> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_ACQUIRE_ITEM>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_ACQUIRE_ITEM> Createc2s_ACQUIRE_ITEM(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t item_id = 0) {
  c2s_ACQUIRE_ITEMBuilder builder_(_fbb);
  builder_.add_item_id(item_id);
  return builder_.Finish();
}

struct s2c_ACQUIRE_ITEM FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_ACQUIRE_ITEMBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GET_USER_ID = 4,
    VT_ITEM_OBJ_ID = 6,
    VT_ITEM_DETAIL_ID = 8,
    VT_ITEM_STACK_SIZE = 10
  };
  uint64_t get_user_id() const {
    return GetField<uint64_t>(VT_GET_USER_ID, 0);
  }
  bool mutate_get_user_id(uint64_t _get_user_id = 0) {
    return SetField<uint64_t>(VT_GET_USER_ID, _get_user_id, 0);
  }
  uint64_t item_obj_id() const {
    return GetField<uint64_t>(VT_ITEM_OBJ_ID, 0);
  }
  bool mutate_item_obj_id(uint64_t _item_obj_id = 0) {
    return SetField<uint64_t>(VT_ITEM_OBJ_ID, _item_obj_id, 0);
  }
  uint8_t item_detail_id() const {
    return GetField<uint8_t>(VT_ITEM_DETAIL_ID, 0);
  }
  bool mutate_item_detail_id(uint8_t _item_detail_id = 0) {
    return SetField<uint8_t>(VT_ITEM_DETAIL_ID, _item_detail_id, 0);
  }
  uint8_t item_stack_size() const {
    return GetField<uint8_t>(VT_ITEM_STACK_SIZE, 0);
  }
  bool mutate_item_stack_size(uint8_t _item_stack_size = 0) {
    return SetField<uint8_t>(VT_ITEM_STACK_SIZE, _item_stack_size, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_GET_USER_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_ITEM_OBJ_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_ITEM_DETAIL_ID, 1) &&
           VerifyField<uint8_t>(verifier, VT_ITEM_STACK_SIZE, 1) &&
           verifier.EndTable();
  }
};

struct s2c_ACQUIRE_ITEMBuilder {
  typedef s2c_ACQUIRE_ITEM Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_get_user_id(uint64_t get_user_id) {
    fbb_.AddElement<uint64_t>(s2c_ACQUIRE_ITEM::VT_GET_USER_ID, get_user_id, 0);
  }
  void add_item_obj_id(uint64_t item_obj_id) {
    fbb_.AddElement<uint64_t>(s2c_ACQUIRE_ITEM::VT_ITEM_OBJ_ID, item_obj_id, 0);
  }
  void add_item_detail_id(uint8_t item_detail_id) {
    fbb_.AddElement<uint8_t>(s2c_ACQUIRE_ITEM::VT_ITEM_DETAIL_ID, item_detail_id, 0);
  }
  void add_item_stack_size(uint8_t item_stack_size) {
    fbb_.AddElement<uint8_t>(s2c_ACQUIRE_ITEM::VT_ITEM_STACK_SIZE, item_stack_size, 0);
  }
  explicit s2c_ACQUIRE_ITEMBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_ACQUIRE_ITEM> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_ACQUIRE_ITEM>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_ACQUIRE_ITEM> Creates2c_ACQUIRE_ITEM(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t get_user_id = 0,
    uint64_t item_obj_id = 0,
    uint8_t item_detail_id = 0,
    uint8_t item_stack_size = 0) {
  s2c_ACQUIRE_ITEMBuilder builder_(_fbb);
  builder_.add_item_obj_id(item_obj_id);
  builder_.add_get_user_id(get_user_id);
  builder_.add_item_stack_size(item_stack_size);
  builder_.add_item_detail_id(item_detail_id);
  return builder_.Finish();
}

struct c2s_REQUEST_QUICK_SLOT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_REQUEST_QUICK_SLOTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEM_ID = 4,
    VT_QUICK_SLOT_IDX = 6
  };
  uint8_t item_id() const {
    return GetField<uint8_t>(VT_ITEM_ID, 0);
  }
  bool mutate_item_id(uint8_t _item_id = 0) {
    return SetField<uint8_t>(VT_ITEM_ID, _item_id, 0);
  }
  uint8_t quick_slot_idx() const {
    return GetField<uint8_t>(VT_QUICK_SLOT_IDX, 0);
  }
  bool mutate_quick_slot_idx(uint8_t _quick_slot_idx = 0) {
    return SetField<uint8_t>(VT_QUICK_SLOT_IDX, _quick_slot_idx, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ITEM_ID, 1) &&
           VerifyField<uint8_t>(verifier, VT_QUICK_SLOT_IDX, 1) &&
           verifier.EndTable();
  }
};

struct c2s_REQUEST_QUICK_SLOTBuilder {
  typedef c2s_REQUEST_QUICK_SLOT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_item_id(uint8_t item_id) {
    fbb_.AddElement<uint8_t>(c2s_REQUEST_QUICK_SLOT::VT_ITEM_ID, item_id, 0);
  }
  void add_quick_slot_idx(uint8_t quick_slot_idx) {
    fbb_.AddElement<uint8_t>(c2s_REQUEST_QUICK_SLOT::VT_QUICK_SLOT_IDX, quick_slot_idx, 0);
  }
  explicit c2s_REQUEST_QUICK_SLOTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_REQUEST_QUICK_SLOT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_REQUEST_QUICK_SLOT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_REQUEST_QUICK_SLOT> Createc2s_REQUEST_QUICK_SLOT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t item_id = 0,
    uint8_t quick_slot_idx = 0) {
  c2s_REQUEST_QUICK_SLOTBuilder builder_(_fbb);
  builder_.add_quick_slot_idx(quick_slot_idx);
  builder_.add_item_id(item_id);
  return builder_.Finish();
}

struct c2s_USE_QUICK_SLOT_ITEM FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_USE_QUICK_SLOT_ITEMBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUICK_SLOT_IDX = 4
  };
  uint8_t quick_slot_idx() const {
    return GetField<uint8_t>(VT_QUICK_SLOT_IDX, 0);
  }
  bool mutate_quick_slot_idx(uint8_t _quick_slot_idx = 0) {
    return SetField<uint8_t>(VT_QUICK_SLOT_IDX, _quick_slot_idx, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_QUICK_SLOT_IDX, 1) &&
           verifier.EndTable();
  }
};

struct c2s_USE_QUICK_SLOT_ITEMBuilder {
  typedef c2s_USE_QUICK_SLOT_ITEM Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_quick_slot_idx(uint8_t quick_slot_idx) {
    fbb_.AddElement<uint8_t>(c2s_USE_QUICK_SLOT_ITEM::VT_QUICK_SLOT_IDX, quick_slot_idx, 0);
  }
  explicit c2s_USE_QUICK_SLOT_ITEMBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_USE_QUICK_SLOT_ITEM> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_USE_QUICK_SLOT_ITEM>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_USE_QUICK_SLOT_ITEM> Createc2s_USE_QUICK_SLOT_ITEM(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t quick_slot_idx = 0) {
  c2s_USE_QUICK_SLOT_ITEMBuilder builder_(_fbb);
  builder_.add_quick_slot_idx(quick_slot_idx);
  return builder_.Finish();
}

struct s2c_USE_QUICK_SLOT_ITEM FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_USE_QUICK_SLOT_ITEMBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USE_USER_ID = 4,
    VT_ITEM_ID = 6,
    VT_QUICK_SLOT_IDX = 8
  };
  uint64_t use_user_id() const {
    return GetField<uint64_t>(VT_USE_USER_ID, 0);
  }
  bool mutate_use_user_id(uint64_t _use_user_id = 0) {
    return SetField<uint64_t>(VT_USE_USER_ID, _use_user_id, 0);
  }
  uint8_t item_id() const {
    return GetField<uint8_t>(VT_ITEM_ID, 0);
  }
  bool mutate_item_id(uint8_t _item_id = 0) {
    return SetField<uint8_t>(VT_ITEM_ID, _item_id, 0);
  }
  uint8_t quick_slot_idx() const {
    return GetField<uint8_t>(VT_QUICK_SLOT_IDX, 0);
  }
  bool mutate_quick_slot_idx(uint8_t _quick_slot_idx = 0) {
    return SetField<uint8_t>(VT_QUICK_SLOT_IDX, _quick_slot_idx, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_USE_USER_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_ITEM_ID, 1) &&
           VerifyField<uint8_t>(verifier, VT_QUICK_SLOT_IDX, 1) &&
           verifier.EndTable();
  }
};

struct s2c_USE_QUICK_SLOT_ITEMBuilder {
  typedef s2c_USE_QUICK_SLOT_ITEM Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_use_user_id(uint64_t use_user_id) {
    fbb_.AddElement<uint64_t>(s2c_USE_QUICK_SLOT_ITEM::VT_USE_USER_ID, use_user_id, 0);
  }
  void add_item_id(uint8_t item_id) {
    fbb_.AddElement<uint8_t>(s2c_USE_QUICK_SLOT_ITEM::VT_ITEM_ID, item_id, 0);
  }
  void add_quick_slot_idx(uint8_t quick_slot_idx) {
    fbb_.AddElement<uint8_t>(s2c_USE_QUICK_SLOT_ITEM::VT_QUICK_SLOT_IDX, quick_slot_idx, 0);
  }
  explicit s2c_USE_QUICK_SLOT_ITEMBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_USE_QUICK_SLOT_ITEM> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_USE_QUICK_SLOT_ITEM>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_USE_QUICK_SLOT_ITEM> Creates2c_USE_QUICK_SLOT_ITEM(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t use_user_id = 0,
    uint8_t item_id = 0,
    uint8_t quick_slot_idx = 0) {
  s2c_USE_QUICK_SLOT_ITEMBuilder builder_(_fbb);
  builder_.add_use_user_id(use_user_id);
  builder_.add_quick_slot_idx(quick_slot_idx);
  builder_.add_item_id(item_id);
  return builder_.Finish();
}

struct c2s_CRAFT_ITEM FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_CRAFT_ITEMBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RECIPE_ID = 4
  };
  uint8_t recipe_id() const {
    return GetField<uint8_t>(VT_RECIPE_ID, 0);
  }
  bool mutate_recipe_id(uint8_t _recipe_id = 0) {
    return SetField<uint8_t>(VT_RECIPE_ID, _recipe_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_RECIPE_ID, 1) &&
           verifier.EndTable();
  }
};

struct c2s_CRAFT_ITEMBuilder {
  typedef c2s_CRAFT_ITEM Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_recipe_id(uint8_t recipe_id) {
    fbb_.AddElement<uint8_t>(c2s_CRAFT_ITEM::VT_RECIPE_ID, recipe_id, 0);
  }
  explicit c2s_CRAFT_ITEMBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_CRAFT_ITEM> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_CRAFT_ITEM>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_CRAFT_ITEM> Createc2s_CRAFT_ITEM(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t recipe_id = 0) {
  c2s_CRAFT_ITEMBuilder builder_(_fbb);
  builder_.add_recipe_id(recipe_id);
  return builder_.Finish();
}

struct s2c_CRAFT_ITEM FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_CRAFT_ITEMBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RECIPE_ID = 4
  };
  uint8_t recipe_id() const {
    return GetField<uint8_t>(VT_RECIPE_ID, 0);
  }
  bool mutate_recipe_id(uint8_t _recipe_id = 0) {
    return SetField<uint8_t>(VT_RECIPE_ID, _recipe_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_RECIPE_ID, 1) &&
           verifier.EndTable();
  }
};

struct s2c_CRAFT_ITEMBuilder {
  typedef s2c_CRAFT_ITEM Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_recipe_id(uint8_t recipe_id) {
    fbb_.AddElement<uint8_t>(s2c_CRAFT_ITEM::VT_RECIPE_ID, recipe_id, 0);
  }
  explicit s2c_CRAFT_ITEMBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_CRAFT_ITEM> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_CRAFT_ITEM>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_CRAFT_ITEM> Creates2c_CRAFT_ITEM(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t recipe_id = 0) {
  s2c_CRAFT_ITEMBuilder builder_(_fbb);
  builder_.add_recipe_id(recipe_id);
  return builder_.Finish();
}

struct c2s_REGISTER_PARTY_QUEST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_REGISTER_PARTY_QUESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUEST_ID = 4
  };
  int32_t quest_id() const {
    return GetField<int32_t>(VT_QUEST_ID, 0);
  }
  bool mutate_quest_id(int32_t _quest_id = 0) {
    return SetField<int32_t>(VT_QUEST_ID, _quest_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_QUEST_ID, 4) &&
           verifier.EndTable();
  }
};

struct c2s_REGISTER_PARTY_QUESTBuilder {
  typedef c2s_REGISTER_PARTY_QUEST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_quest_id(int32_t quest_id) {
    fbb_.AddElement<int32_t>(c2s_REGISTER_PARTY_QUEST::VT_QUEST_ID, quest_id, 0);
  }
  explicit c2s_REGISTER_PARTY_QUESTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_REGISTER_PARTY_QUEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_REGISTER_PARTY_QUEST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_REGISTER_PARTY_QUEST> Createc2s_REGISTER_PARTY_QUEST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t quest_id = 0) {
  c2s_REGISTER_PARTY_QUESTBuilder builder_(_fbb);
  builder_.add_quest_id(quest_id);
  return builder_.Finish();
}

struct s2c_REGISTER_PARTY_QUEST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_REGISTER_PARTY_QUESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUEST_ID = 4
  };
  int32_t quest_id() const {
    return GetField<int32_t>(VT_QUEST_ID, 0);
  }
  bool mutate_quest_id(int32_t _quest_id = 0) {
    return SetField<int32_t>(VT_QUEST_ID, _quest_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_QUEST_ID, 4) &&
           verifier.EndTable();
  }
};

struct s2c_REGISTER_PARTY_QUESTBuilder {
  typedef s2c_REGISTER_PARTY_QUEST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_quest_id(int32_t quest_id) {
    fbb_.AddElement<int32_t>(s2c_REGISTER_PARTY_QUEST::VT_QUEST_ID, quest_id, 0);
  }
  explicit s2c_REGISTER_PARTY_QUESTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_REGISTER_PARTY_QUEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_REGISTER_PARTY_QUEST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_REGISTER_PARTY_QUEST> Creates2c_REGISTER_PARTY_QUEST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t quest_id = 0) {
  s2c_REGISTER_PARTY_QUESTBuilder builder_(_fbb);
  builder_.add_quest_id(quest_id);
  return builder_.Finish();
}

struct c2s_ACQUIRE_PARTY_LIST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_ACQUIRE_PARTY_LISTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_QUEST_ID = 4
  };
  int32_t target_quest_id() const {
    return GetField<int32_t>(VT_TARGET_QUEST_ID, 0);
  }
  bool mutate_target_quest_id(int32_t _target_quest_id = 0) {
    return SetField<int32_t>(VT_TARGET_QUEST_ID, _target_quest_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TARGET_QUEST_ID, 4) &&
           verifier.EndTable();
  }
};

struct c2s_ACQUIRE_PARTY_LISTBuilder {
  typedef c2s_ACQUIRE_PARTY_LIST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_quest_id(int32_t target_quest_id) {
    fbb_.AddElement<int32_t>(c2s_ACQUIRE_PARTY_LIST::VT_TARGET_QUEST_ID, target_quest_id, 0);
  }
  explicit c2s_ACQUIRE_PARTY_LISTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_ACQUIRE_PARTY_LIST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_ACQUIRE_PARTY_LIST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_ACQUIRE_PARTY_LIST> Createc2s_ACQUIRE_PARTY_LIST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t target_quest_id = 0) {
  c2s_ACQUIRE_PARTY_LISTBuilder builder_(_fbb);
  builder_.add_target_quest_id(target_quest_id);
  return builder_.Finish();
}

struct s2c_ACQUIRE_PARTY_LIST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_ACQUIRE_PARTY_LISTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARTY_LEADER_IDS = 4,
    VT_TARGET_QUEST_ID = 6
  };
  const ::flatbuffers::Vector<uint32_t> *party_leader_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_PARTY_LEADER_IDS);
  }
  ::flatbuffers::Vector<uint32_t> *mutable_party_leader_ids() {
    return GetPointer<::flatbuffers::Vector<uint32_t> *>(VT_PARTY_LEADER_IDS);
  }
  int32_t target_quest_id() const {
    return GetField<int32_t>(VT_TARGET_QUEST_ID, 0);
  }
  bool mutate_target_quest_id(int32_t _target_quest_id = 0) {
    return SetField<int32_t>(VT_TARGET_QUEST_ID, _target_quest_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PARTY_LEADER_IDS) &&
           verifier.VerifyVector(party_leader_ids()) &&
           VerifyField<int32_t>(verifier, VT_TARGET_QUEST_ID, 4) &&
           verifier.EndTable();
  }
};

struct s2c_ACQUIRE_PARTY_LISTBuilder {
  typedef s2c_ACQUIRE_PARTY_LIST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_party_leader_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> party_leader_ids) {
    fbb_.AddOffset(s2c_ACQUIRE_PARTY_LIST::VT_PARTY_LEADER_IDS, party_leader_ids);
  }
  void add_target_quest_id(int32_t target_quest_id) {
    fbb_.AddElement<int32_t>(s2c_ACQUIRE_PARTY_LIST::VT_TARGET_QUEST_ID, target_quest_id, 0);
  }
  explicit s2c_ACQUIRE_PARTY_LISTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_ACQUIRE_PARTY_LIST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_ACQUIRE_PARTY_LIST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_ACQUIRE_PARTY_LIST> Creates2c_ACQUIRE_PARTY_LIST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> party_leader_ids = 0,
    int32_t target_quest_id = 0) {
  s2c_ACQUIRE_PARTY_LISTBuilder builder_(_fbb);
  builder_.add_target_quest_id(target_quest_id);
  builder_.add_party_leader_ids(party_leader_ids);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<s2c_ACQUIRE_PARTY_LIST> Creates2c_ACQUIRE_PARTY_LISTDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *party_leader_ids = nullptr,
    int32_t target_quest_id = 0) {
  auto party_leader_ids__ = party_leader_ids ? _fbb.CreateVector<uint32_t>(*party_leader_ids) : 0;
  return Nagox::Protocol::Creates2c_ACQUIRE_PARTY_LIST(
      _fbb,
      party_leader_ids__,
      target_quest_id);
}

struct c2s_INVITE_PARTY_QUEST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_INVITE_PARTY_QUESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_USER_ID = 4
  };
  uint32_t target_user_id() const {
    return GetField<uint32_t>(VT_TARGET_USER_ID, 0);
  }
  bool mutate_target_user_id(uint32_t _target_user_id = 0) {
    return SetField<uint32_t>(VT_TARGET_USER_ID, _target_user_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_USER_ID, 4) &&
           verifier.EndTable();
  }
};

struct c2s_INVITE_PARTY_QUESTBuilder {
  typedef c2s_INVITE_PARTY_QUEST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_user_id(uint32_t target_user_id) {
    fbb_.AddElement<uint32_t>(c2s_INVITE_PARTY_QUEST::VT_TARGET_USER_ID, target_user_id, 0);
  }
  explicit c2s_INVITE_PARTY_QUESTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_INVITE_PARTY_QUEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_INVITE_PARTY_QUEST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_INVITE_PARTY_QUEST> Createc2s_INVITE_PARTY_QUEST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_user_id = 0) {
  c2s_INVITE_PARTY_QUESTBuilder builder_(_fbb);
  builder_.add_target_user_id(target_user_id);
  return builder_.Finish();
}

struct s2c_INVITE_PARTY_QUEST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_INVITE_PARTY_QUESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PARTY_LEADER_ID = 4,
    VT_TARGET_PARTY_QUEST_ID = 6
  };
  uint32_t target_party_leader_id() const {
    return GetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, 0);
  }
  bool mutate_target_party_leader_id(uint32_t _target_party_leader_id = 0) {
    return SetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, _target_party_leader_id, 0);
  }
  int32_t target_party_quest_id() const {
    return GetField<int32_t>(VT_TARGET_PARTY_QUEST_ID, 0);
  }
  bool mutate_target_party_quest_id(int32_t _target_party_quest_id = 0) {
    return SetField<int32_t>(VT_TARGET_PARTY_QUEST_ID, _target_party_quest_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_PARTY_LEADER_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_TARGET_PARTY_QUEST_ID, 4) &&
           verifier.EndTable();
  }
};

struct s2c_INVITE_PARTY_QUESTBuilder {
  typedef s2c_INVITE_PARTY_QUEST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_party_leader_id(uint32_t target_party_leader_id) {
    fbb_.AddElement<uint32_t>(s2c_INVITE_PARTY_QUEST::VT_TARGET_PARTY_LEADER_ID, target_party_leader_id, 0);
  }
  void add_target_party_quest_id(int32_t target_party_quest_id) {
    fbb_.AddElement<int32_t>(s2c_INVITE_PARTY_QUEST::VT_TARGET_PARTY_QUEST_ID, target_party_quest_id, 0);
  }
  explicit s2c_INVITE_PARTY_QUESTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_INVITE_PARTY_QUEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_INVITE_PARTY_QUEST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_INVITE_PARTY_QUEST> Creates2c_INVITE_PARTY_QUEST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_party_leader_id = 0,
    int32_t target_party_quest_id = 0) {
  s2c_INVITE_PARTY_QUESTBuilder builder_(_fbb);
  builder_.add_target_party_quest_id(target_party_quest_id);
  builder_.add_target_party_leader_id(target_party_leader_id);
  return builder_.Finish();
}

struct c2s_INVITE_PARTY_RESULT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_INVITE_PARTY_RESULTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PARTY_LEADER_ID = 4,
    VT_IS_ACCEPT = 6
  };
  uint32_t target_party_leader_id() const {
    return GetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, 0);
  }
  bool mutate_target_party_leader_id(uint32_t _target_party_leader_id = 0) {
    return SetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, _target_party_leader_id, 0);
  }
  bool is_accept() const {
    return GetField<uint8_t>(VT_IS_ACCEPT, 0) != 0;
  }
  bool mutate_is_accept(bool _is_accept = 0) {
    return SetField<uint8_t>(VT_IS_ACCEPT, static_cast<uint8_t>(_is_accept), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_PARTY_LEADER_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_IS_ACCEPT, 1) &&
           verifier.EndTable();
  }
};

struct c2s_INVITE_PARTY_RESULTBuilder {
  typedef c2s_INVITE_PARTY_RESULT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_party_leader_id(uint32_t target_party_leader_id) {
    fbb_.AddElement<uint32_t>(c2s_INVITE_PARTY_RESULT::VT_TARGET_PARTY_LEADER_ID, target_party_leader_id, 0);
  }
  void add_is_accept(bool is_accept) {
    fbb_.AddElement<uint8_t>(c2s_INVITE_PARTY_RESULT::VT_IS_ACCEPT, static_cast<uint8_t>(is_accept), 0);
  }
  explicit c2s_INVITE_PARTY_RESULTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_INVITE_PARTY_RESULT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_INVITE_PARTY_RESULT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_INVITE_PARTY_RESULT> Createc2s_INVITE_PARTY_RESULT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_party_leader_id = 0,
    bool is_accept = false) {
  c2s_INVITE_PARTY_RESULTBuilder builder_(_fbb);
  builder_.add_target_party_leader_id(target_party_leader_id);
  builder_.add_is_accept(is_accept);
  return builder_.Finish();
}

struct s2c_INVITE_PARTY_RESULT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_INVITE_PARTY_RESULTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PARTY_LEADER_ID = 4,
    VT_TARGET_USER_ID = 6,
    VT_INVITE_RESULT = 8
  };
  uint32_t target_party_leader_id() const {
    return GetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, 0);
  }
  bool mutate_target_party_leader_id(uint32_t _target_party_leader_id = 0) {
    return SetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, _target_party_leader_id, 0);
  }
  uint32_t target_user_id() const {
    return GetField<uint32_t>(VT_TARGET_USER_ID, 0);
  }
  bool mutate_target_user_id(uint32_t _target_user_id = 0) {
    return SetField<uint32_t>(VT_TARGET_USER_ID, _target_user_id, 0);
  }
  bool invite_result() const {
    return GetField<uint8_t>(VT_INVITE_RESULT, 0) != 0;
  }
  bool mutate_invite_result(bool _invite_result = 0) {
    return SetField<uint8_t>(VT_INVITE_RESULT, static_cast<uint8_t>(_invite_result), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_PARTY_LEADER_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_USER_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_INVITE_RESULT, 1) &&
           verifier.EndTable();
  }
};

struct s2c_INVITE_PARTY_RESULTBuilder {
  typedef s2c_INVITE_PARTY_RESULT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_party_leader_id(uint32_t target_party_leader_id) {
    fbb_.AddElement<uint32_t>(s2c_INVITE_PARTY_RESULT::VT_TARGET_PARTY_LEADER_ID, target_party_leader_id, 0);
  }
  void add_target_user_id(uint32_t target_user_id) {
    fbb_.AddElement<uint32_t>(s2c_INVITE_PARTY_RESULT::VT_TARGET_USER_ID, target_user_id, 0);
  }
  void add_invite_result(bool invite_result) {
    fbb_.AddElement<uint8_t>(s2c_INVITE_PARTY_RESULT::VT_INVITE_RESULT, static_cast<uint8_t>(invite_result), 0);
  }
  explicit s2c_INVITE_PARTY_RESULTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_INVITE_PARTY_RESULT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_INVITE_PARTY_RESULT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_INVITE_PARTY_RESULT> Creates2c_INVITE_PARTY_RESULT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_party_leader_id = 0,
    uint32_t target_user_id = 0,
    bool invite_result = false) {
  s2c_INVITE_PARTY_RESULTBuilder builder_(_fbb);
  builder_.add_target_user_id(target_user_id);
  builder_.add_target_party_leader_id(target_party_leader_id);
  builder_.add_invite_result(invite_result);
  return builder_.Finish();
}

struct c2s_PARTY_JOIN_REQUEST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_PARTY_JOIN_REQUESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PARTY_LEADER_ID = 4,
    VT_TARGET_PARTY_QUEST_ID = 6
  };
  uint32_t target_party_leader_id() const {
    return GetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, 0);
  }
  bool mutate_target_party_leader_id(uint32_t _target_party_leader_id = 0) {
    return SetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, _target_party_leader_id, 0);
  }
  int32_t target_party_quest_id() const {
    return GetField<int32_t>(VT_TARGET_PARTY_QUEST_ID, 0);
  }
  bool mutate_target_party_quest_id(int32_t _target_party_quest_id = 0) {
    return SetField<int32_t>(VT_TARGET_PARTY_QUEST_ID, _target_party_quest_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_PARTY_LEADER_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_TARGET_PARTY_QUEST_ID, 4) &&
           verifier.EndTable();
  }
};

struct c2s_PARTY_JOIN_REQUESTBuilder {
  typedef c2s_PARTY_JOIN_REQUEST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_party_leader_id(uint32_t target_party_leader_id) {
    fbb_.AddElement<uint32_t>(c2s_PARTY_JOIN_REQUEST::VT_TARGET_PARTY_LEADER_ID, target_party_leader_id, 0);
  }
  void add_target_party_quest_id(int32_t target_party_quest_id) {
    fbb_.AddElement<int32_t>(c2s_PARTY_JOIN_REQUEST::VT_TARGET_PARTY_QUEST_ID, target_party_quest_id, 0);
  }
  explicit c2s_PARTY_JOIN_REQUESTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_PARTY_JOIN_REQUEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_PARTY_JOIN_REQUEST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_PARTY_JOIN_REQUEST> Createc2s_PARTY_JOIN_REQUEST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_party_leader_id = 0,
    int32_t target_party_quest_id = 0) {
  c2s_PARTY_JOIN_REQUESTBuilder builder_(_fbb);
  builder_.add_target_party_quest_id(target_party_quest_id);
  builder_.add_target_party_leader_id(target_party_leader_id);
  return builder_.Finish();
}

struct s2c_PARTY_JOIN_REQUEST FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_PARTY_JOIN_REQUESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_USER_ID = 4
  };
  uint32_t target_user_id() const {
    return GetField<uint32_t>(VT_TARGET_USER_ID, 0);
  }
  bool mutate_target_user_id(uint32_t _target_user_id = 0) {
    return SetField<uint32_t>(VT_TARGET_USER_ID, _target_user_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_USER_ID, 4) &&
           verifier.EndTable();
  }
};

struct s2c_PARTY_JOIN_REQUESTBuilder {
  typedef s2c_PARTY_JOIN_REQUEST Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_user_id(uint32_t target_user_id) {
    fbb_.AddElement<uint32_t>(s2c_PARTY_JOIN_REQUEST::VT_TARGET_USER_ID, target_user_id, 0);
  }
  explicit s2c_PARTY_JOIN_REQUESTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_PARTY_JOIN_REQUEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_PARTY_JOIN_REQUEST>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_PARTY_JOIN_REQUEST> Creates2c_PARTY_JOIN_REQUEST(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_user_id = 0) {
  s2c_PARTY_JOIN_REQUESTBuilder builder_(_fbb);
  builder_.add_target_user_id(target_user_id);
  return builder_.Finish();
}

struct c2s_PARTY_JOIN_REQUEST_RESULT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_PARTY_JOIN_REQUEST_RESULTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_PARTY_LEADER_ID = 4,
    VT_TARGET_USER_ID = 6,
    VT_REQUEST_RESULT = 8
  };
  uint32_t target_party_leader_id() const {
    return GetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, 0);
  }
  bool mutate_target_party_leader_id(uint32_t _target_party_leader_id = 0) {
    return SetField<uint32_t>(VT_TARGET_PARTY_LEADER_ID, _target_party_leader_id, 0);
  }
  uint32_t target_user_id() const {
    return GetField<uint32_t>(VT_TARGET_USER_ID, 0);
  }
  bool mutate_target_user_id(uint32_t _target_user_id = 0) {
    return SetField<uint32_t>(VT_TARGET_USER_ID, _target_user_id, 0);
  }
  bool request_result() const {
    return GetField<uint8_t>(VT_REQUEST_RESULT, 0) != 0;
  }
  bool mutate_request_result(bool _request_result = 0) {
    return SetField<uint8_t>(VT_REQUEST_RESULT, static_cast<uint8_t>(_request_result), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_PARTY_LEADER_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_USER_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_REQUEST_RESULT, 1) &&
           verifier.EndTable();
  }
};

struct c2s_PARTY_JOIN_REQUEST_RESULTBuilder {
  typedef c2s_PARTY_JOIN_REQUEST_RESULT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_party_leader_id(uint32_t target_party_leader_id) {
    fbb_.AddElement<uint32_t>(c2s_PARTY_JOIN_REQUEST_RESULT::VT_TARGET_PARTY_LEADER_ID, target_party_leader_id, 0);
  }
  void add_target_user_id(uint32_t target_user_id) {
    fbb_.AddElement<uint32_t>(c2s_PARTY_JOIN_REQUEST_RESULT::VT_TARGET_USER_ID, target_user_id, 0);
  }
  void add_request_result(bool request_result) {
    fbb_.AddElement<uint8_t>(c2s_PARTY_JOIN_REQUEST_RESULT::VT_REQUEST_RESULT, static_cast<uint8_t>(request_result), 0);
  }
  explicit c2s_PARTY_JOIN_REQUEST_RESULTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_PARTY_JOIN_REQUEST_RESULT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_PARTY_JOIN_REQUEST_RESULT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_PARTY_JOIN_REQUEST_RESULT> Createc2s_PARTY_JOIN_REQUEST_RESULT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_party_leader_id = 0,
    uint32_t target_user_id = 0,
    bool request_result = false) {
  c2s_PARTY_JOIN_REQUEST_RESULTBuilder builder_(_fbb);
  builder_.add_target_user_id(target_user_id);
  builder_.add_target_party_leader_id(target_party_leader_id);
  builder_.add_request_result(request_result);
  return builder_.Finish();
}

struct s2c_PARTY_JOIN_REQUEST_RESULT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_PARTY_JOIN_REQUEST_RESULTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_USER_ID = 4,
    VT_REQUEST_RESULT = 6
  };
  uint32_t target_user_id() const {
    return GetField<uint32_t>(VT_TARGET_USER_ID, 0);
  }
  bool mutate_target_user_id(uint32_t _target_user_id = 0) {
    return SetField<uint32_t>(VT_TARGET_USER_ID, _target_user_id, 0);
  }
  bool request_result() const {
    return GetField<uint8_t>(VT_REQUEST_RESULT, 0) != 0;
  }
  bool mutate_request_result(bool _request_result = 0) {
    return SetField<uint8_t>(VT_REQUEST_RESULT, static_cast<uint8_t>(_request_result), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_USER_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_REQUEST_RESULT, 1) &&
           verifier.EndTable();
  }
};

struct s2c_PARTY_JOIN_REQUEST_RESULTBuilder {
  typedef s2c_PARTY_JOIN_REQUEST_RESULT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_user_id(uint32_t target_user_id) {
    fbb_.AddElement<uint32_t>(s2c_PARTY_JOIN_REQUEST_RESULT::VT_TARGET_USER_ID, target_user_id, 0);
  }
  void add_request_result(bool request_result) {
    fbb_.AddElement<uint8_t>(s2c_PARTY_JOIN_REQUEST_RESULT::VT_REQUEST_RESULT, static_cast<uint8_t>(request_result), 0);
  }
  explicit s2c_PARTY_JOIN_REQUEST_RESULTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_PARTY_JOIN_REQUEST_RESULT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_PARTY_JOIN_REQUEST_RESULT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_PARTY_JOIN_REQUEST_RESULT> Creates2c_PARTY_JOIN_REQUEST_RESULT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_user_id = 0,
    bool request_result = false) {
  s2c_PARTY_JOIN_REQUEST_RESULTBuilder builder_(_fbb);
  builder_.add_target_user_id(target_user_id);
  builder_.add_request_result(request_result);
  return builder_.Finish();
}

struct s2c_PARTY_JOIN_NEW_PLAYER FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_PARTY_JOIN_NEW_PLAYERBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TARGET_USER_ID = 4
  };
  uint32_t target_user_id() const {
    return GetField<uint32_t>(VT_TARGET_USER_ID, 0);
  }
  bool mutate_target_user_id(uint32_t _target_user_id = 0) {
    return SetField<uint32_t>(VT_TARGET_USER_ID, _target_user_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_USER_ID, 4) &&
           verifier.EndTable();
  }
};

struct s2c_PARTY_JOIN_NEW_PLAYERBuilder {
  typedef s2c_PARTY_JOIN_NEW_PLAYER Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_target_user_id(uint32_t target_user_id) {
    fbb_.AddElement<uint32_t>(s2c_PARTY_JOIN_NEW_PLAYER::VT_TARGET_USER_ID, target_user_id, 0);
  }
  explicit s2c_PARTY_JOIN_NEW_PLAYERBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_PARTY_JOIN_NEW_PLAYER> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_PARTY_JOIN_NEW_PLAYER>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_PARTY_JOIN_NEW_PLAYER> Creates2c_PARTY_JOIN_NEW_PLAYER(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t target_user_id = 0) {
  s2c_PARTY_JOIN_NEW_PLAYERBuilder builder_(_fbb);
  builder_.add_target_user_id(target_user_id);
  return builder_.Finish();
}

struct c2s_QUEST_START FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_QUEST_STARTBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct c2s_QUEST_STARTBuilder {
  typedef c2s_QUEST_START Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit c2s_QUEST_STARTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_QUEST_START> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_QUEST_START>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_QUEST_START> Createc2s_QUEST_START(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  c2s_QUEST_STARTBuilder builder_(_fbb);
  return builder_.Finish();
}

struct c2s_QUEST_END FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_QUEST_ENDBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct c2s_QUEST_ENDBuilder {
  typedef c2s_QUEST_END Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit c2s_QUEST_ENDBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_QUEST_END> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_QUEST_END>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_QUEST_END> Createc2s_QUEST_END(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  c2s_QUEST_ENDBuilder builder_(_fbb);
  return builder_.Finish();
}

struct c2s_PARTY_OUT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef c2s_PARTY_OUTBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct c2s_PARTY_OUTBuilder {
  typedef c2s_PARTY_OUT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit c2s_PARTY_OUTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<c2s_PARTY_OUT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<c2s_PARTY_OUT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<c2s_PARTY_OUT> Createc2s_PARTY_OUT(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  c2s_PARTY_OUTBuilder builder_(_fbb);
  return builder_.Finish();
}

struct s2c_PARTY_OUT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_PARTY_OUTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OUT_USER_ID = 4,
    VT_IS_LEADER = 6
  };
  uint32_t out_user_id() const {
    return GetField<uint32_t>(VT_OUT_USER_ID, 0);
  }
  bool mutate_out_user_id(uint32_t _out_user_id = 0) {
    return SetField<uint32_t>(VT_OUT_USER_ID, _out_user_id, 0);
  }
  bool is_leader() const {
    return GetField<uint8_t>(VT_IS_LEADER, 0) != 0;
  }
  bool mutate_is_leader(bool _is_leader = 0) {
    return SetField<uint8_t>(VT_IS_LEADER, static_cast<uint8_t>(_is_leader), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_OUT_USER_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_IS_LEADER, 1) &&
           verifier.EndTable();
  }
};

struct s2c_PARTY_OUTBuilder {
  typedef s2c_PARTY_OUT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_out_user_id(uint32_t out_user_id) {
    fbb_.AddElement<uint32_t>(s2c_PARTY_OUT::VT_OUT_USER_ID, out_user_id, 0);
  }
  void add_is_leader(bool is_leader) {
    fbb_.AddElement<uint8_t>(s2c_PARTY_OUT::VT_IS_LEADER, static_cast<uint8_t>(is_leader), 0);
  }
  explicit s2c_PARTY_OUTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_PARTY_OUT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_PARTY_OUT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_PARTY_OUT> Creates2c_PARTY_OUT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t out_user_id = 0,
    bool is_leader = false) {
  s2c_PARTY_OUTBuilder builder_(_fbb);
  builder_.add_out_user_id(out_user_id);
  builder_.add_is_leader(is_leader);
  return builder_.Finish();
}

struct s2c_PARTY_QUEST_CLEAR FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_PARTY_QUEST_CLEARBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARTY_QUEST_ID = 4
  };
  int32_t party_quest_id() const {
    return GetField<int32_t>(VT_PARTY_QUEST_ID, 0);
  }
  bool mutate_party_quest_id(int32_t _party_quest_id = 0) {
    return SetField<int32_t>(VT_PARTY_QUEST_ID, _party_quest_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PARTY_QUEST_ID, 4) &&
           verifier.EndTable();
  }
};

struct s2c_PARTY_QUEST_CLEARBuilder {
  typedef s2c_PARTY_QUEST_CLEAR Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_party_quest_id(int32_t party_quest_id) {
    fbb_.AddElement<int32_t>(s2c_PARTY_QUEST_CLEAR::VT_PARTY_QUEST_ID, party_quest_id, 0);
  }
  explicit s2c_PARTY_QUEST_CLEARBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_PARTY_QUEST_CLEAR> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_PARTY_QUEST_CLEAR>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_PARTY_QUEST_CLEAR> Creates2c_PARTY_QUEST_CLEAR(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t party_quest_id = 0) {
  s2c_PARTY_QUEST_CLEARBuilder builder_(_fbb);
  builder_.add_party_quest_id(party_quest_id);
  return builder_.Finish();
}

struct s2c_PARTY_MEMBERS_INFORMATION FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef s2c_PARTY_MEMBERS_INFORMATIONBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARTY_MEMBER_IDS = 4
  };
  const ::flatbuffers::Vector<uint32_t> *party_member_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_PARTY_MEMBER_IDS);
  }
  ::flatbuffers::Vector<uint32_t> *mutable_party_member_ids() {
    return GetPointer<::flatbuffers::Vector<uint32_t> *>(VT_PARTY_MEMBER_IDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PARTY_MEMBER_IDS) &&
           verifier.VerifyVector(party_member_ids()) &&
           verifier.EndTable();
  }
};

struct s2c_PARTY_MEMBERS_INFORMATIONBuilder {
  typedef s2c_PARTY_MEMBERS_INFORMATION Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_party_member_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> party_member_ids) {
    fbb_.AddOffset(s2c_PARTY_MEMBERS_INFORMATION::VT_PARTY_MEMBER_IDS, party_member_ids);
  }
  explicit s2c_PARTY_MEMBERS_INFORMATIONBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<s2c_PARTY_MEMBERS_INFORMATION> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<s2c_PARTY_MEMBERS_INFORMATION>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<s2c_PARTY_MEMBERS_INFORMATION> Creates2c_PARTY_MEMBERS_INFORMATION(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> party_member_ids = 0) {
  s2c_PARTY_MEMBERS_INFORMATIONBuilder builder_(_fbb);
  builder_.add_party_member_ids(party_member_ids);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<s2c_PARTY_MEMBERS_INFORMATION> Creates2c_PARTY_MEMBERS_INFORMATIONDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *party_member_ids = nullptr) {
  auto party_member_ids__ = party_member_ids ? _fbb.CreateVector<uint32_t>(*party_member_ids) : 0;
  return Nagox::Protocol::Creates2c_PARTY_MEMBERS_INFORMATION(
      _fbb,
      party_member_ids__);
}

}  // namespace Protocol
}  // namespace Nagox

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_NAGOX_PROTOCOL_H_
